### ISSUE TITLE
Timeline to integrate into aws-amplify?

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [undefobj/hub_reboot#1]
Hey @undefobj,

Sorry for invading your personal repos =)

I'm in the process of doing a major re-architecture of Addison Care (in the wake of CES, which showed me some obvious paths of improvement for our eventual product), and would like to see whether I can use your version or whether I need to fork it as our own dependency until regex and middleware makes Amplify Hub primetime :P 

Thank you so much for this! I really, really appreciate the effort. I've got to say that I had all the ideas kinda coalescing, nebulously, around my subconsciousness, and your Hub.ts redux put them all into reality. So thank you very much for your ideas surrounding regex Hub!! :D

**Comment by undefobj** [comment]
@jkeys-ecg-nmsu we've got a PR now for the implementation in the Amplify repo. We'll try to see what type of testing we can get in the next ~week but feel free to clone that PR #2850.
